# build stage
From node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . . 

RUN npm run build 


# development stage
From node:20-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=build /usr/src/app/dist ./dist

EXPOSE 6060

ENV SOCKET_SERVER_PORT=6060

CMD ["nodemon", "dist/index.js"]
